FORMAT: 1A
HOST: https://servantfornoobies.docs.apiary.io/

# Servant for Noobies (by Noobies)

Lets create the most awesome Cat Photobloging API!


## Cats Collection [/cats]

### List Cats [GET]
+ Response 200 (application/json)
    + Attributes (array[FullCat], fixed-type)

### Create a Cat [POST]
+ Request (application/json)
    + Attributes (Cat)
+ Response 201 (application/json)
    + Attributes (FullCat)

## Individual Cat [/cats/{id}]
+ Parameters
    + id: 2 (number, required) - A cat ID

### Update [PUT]
+ Request (application/json)
    + Attributes (FullCat)
+ Response 201 (application/json)
    + Attributes (FullCat)

### Delete [DELETE]
+ Response 204

### Cat with Pics [GET]
+ Response 200 (application/json)
    + Attributes (RelationalCat)




## Pics [/pics]

### Create [POST]
+ Request (application/json)
    + Attributes (Pic)
+ Response 201 (application/json)
    + Attributes (Pic)

### Delete [DELETE]
+ Request (application/json)
    + Attributes (Pic)
+ Response 204




## Data Structures

### Cat
* name: `Fuzzy Mc Fuzzboots` (string, required)
* age: 4 (number, required)
* color (CatColor, required)

### CatColor (enum)
* DottedBrown
* StripedBrown
* Black

### FullCat (Cat)
* id: 1 (number, required)

### RelationalCat (Cat)
* pics (array[Pic], fixed-type, required)

### Pic
* location (Location, required) Where the pic was taken
* popularity: 99 (number, required) Bounded to 100
* cats (array[number], fixed-type, required) The IDs of the cats in the picture

### Location (enum)
* EastCoast
* Riviera
* Narnia
